### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by MikaelMayer** [ravichugh/sketch-n-sketch#145]
C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:576
                throw new Error(
                ^

Error: Ran into a `Debug.crash` in module `UpdateUtils` on line 2109
The message provided by the code author is:

    Expected only at most one modification at the end of a list, got (11,11,11,[(11,ListElemInsert 1)],[(11,ListElemInsert 1)])
    at C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:576:9
    at C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:54811:12
    at C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:63:33
    at A6 (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:122:25)
    at Function.func (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:62332:20)
    at A5 (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:115:11)
    at Function.func (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:62607:25)
    at A8 (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:133:11)
    at Function.func (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:62767:10)
    at A5 (C:\Users\Mikael\AppData\Roaming\npm\node_modules\http-server-editor\node_modules\sketch-n-sketch\sns.js:115:11)

**Comment by MikaelMayer** [comment]
Minimum reproducing example:

```
list = [1, 2, 3]

<span>@(toString <| list)<br>
@(toString <| list)<br>
@(toString <| list)
</span>
```

Add to the end of each occurrence of the list respectively 4, 5, 6. This reproduces the crash.
